[package]
name = "kiorg"
version = "0.1.0"
edition = "2021"
authors = ["houqp"]

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
chrono = "0.4.40"
humansize = "2.1.3"
toml = "0.8.8"
serde = { version = "1.0.193", features = ["derive"] }
dirs-next = "2.0.0"
