[package]
name = "kiorg"
version = "0.1.0"
edition = "2021"
authors = ["houqp"]
repository = "https://github.com/houqp/kiorg"

[lib]
name = "kiorg"
path = "src/lib.rs"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
chrono = "0.4.40"
humansize = "2.1.3"
toml = "0.8.8"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0"
dirs-next = "2.0.0"
open = "4.0"
pdfium-render = "0"
clap = { version = "4.5.1", features = ["derive"] }
egui_term = { git = "https://github.com/houqp/egui_term.git", rev = "b8b4a1b79e10e07bd64d8104449e8904b466b3cd" }
notify = "8"
egui_extras = { version = "0", features = ["all_loaders"] }
image = { version = "0"}
zip = "2"

[dev-dependencies]
egui_kittest = { version = "0.31.1", features = ["eframe"] }
tempfile = "3.8"
